server:
  # é…ç½®ç«¯å£
  port: 8888

log:
  # é…ç½®æ—¥å¿—è·¯å¾„
  path: logs

env:
  # é…ç½®æ—¥å¿—ç¯å¢ƒåç§°
  name: dev

logging:
  level:
    com.ming.happyclub.web.*: debug # æŒ‡å®šå…·ä½“åŒ…ä¸‹çš„æ—¥å¿—è¾“å‡ºçº§åˆ«

knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: å¿«ä¹éƒ¨
    description: ä¸€ä¸ªåŸºäº Spring Bootã€MyBatis-Plusã€MySQLã€Redisã€ElasticSearchã€MongoDBã€Dockerã€RabbitMQ ç­‰æŠ€æœ¯æ ˆå®ç°çš„ç¤¾åŒºç³»ç»Ÿï¼Œé‡‡ç”¨ä¸»æµçš„äº’è”ç½‘æŠ€æœ¯æ¶æ„ã€å…¨æ–°çš„UIè®¾è®¡ã€æ”¯æŒä¸€é”®æºç éƒ¨ç½²ï¼Œæ‹¥æœ‰å®Œæ•´çš„æ–‡ç« &æ•™ç¨‹å‘å¸ƒ/æœç´¢/è¯„è®º/ç»Ÿè®¡æµç¨‹ç­‰ï¼Œä»£ç å®Œå…¨å¼€æºï¼Œæ²¡æœ‰ä»»ä½•äºŒæ¬¡å°è£…ï¼Œæ˜¯ä¸€ä¸ªéå¸¸é€‚åˆäºŒæ¬¡å¼€å‘/å®æˆ˜çš„ç°ä»£åŒ–ç¤¾åŒºé¡¹ç›®ğŸ‘ ã€‚
    version: 1.0.0
    concat:
      - ECRZ
    email: himing4@163.com